pipeline:
  identifier: Build_POC_KALPESHY_sbt_scoverage_samples_1736311364111
  name: Build sbt-scoverage-samples
  orgIdentifier: default
  projectIdentifier: Shubham
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: POC-KALPESHY/sbt-scoverage-samples
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Sh
                    command: echo Start Ci Process
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: Compile
                  identifier: Compile
                  spec:
                    shell: Sh
                    command: sbt compile
              - step:
                  type: Test
                  name: Test
                  identifier: Test
                  spec:
                    shell: Sh
                    command: sbt test
                    intelligenceMode: true
              - step:
                  type: Run
                  name: Package
                  identifier: Package
                  spec:
                    shell: Sh
                    command: sbt package
              - step:
                  type: S3Upload
                  name: S3Upload_1
                  identifier: S3Upload_1
                  spec:
                    connectorRef: S3
                    region: us-east-1
                    bucket: shubhamdemos3
                    sourcePath: "**/*.jar"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
